file organization

diff --git a/run b/run
--- a/run
+++ b/run
@@ -2,19 +2,33 @@
 
 # Usage
 # Run the code from the file source.fn:
-#   ./run source.fn
+#   ./run static source.fn
 # Convert the code from the file source.fn and store the OCaml code in out.ml: 
-#   ./run source.fn out.ml
+#   ./run static source.fn out.ml
 
-if [ $# -eq 0 ]; then
-	echo "Missing filename argument"
-	echo "Usage: run filename [dest-filename]"
-elif [ $# -eq 1 ]; then
-	camlp4 run.cmo < "$1"
+if [ $# -lt 1 ]; then
+	echo "Missing interpreter mode"
+	echo "Usage: run static|dynamic filename [dest-filename]"
 else
-	# write the output only if the program was parsed successfully
-	if result=$(camlp4 trans.cmo < "$1"; exit ${PIPESTATUS[0]}); then
-    	echo "$result" > "$2"
+	runner=""
+	translator=""
+	if [ $1 == "static" ]; then
+		runner="run_static.cmo"
+		translator="trans_static.cmo"
+	else
+		runner="run_dynamic.cmo"
+		translator="trans_dynamic.cmo"
 	fi
-	
+
+	if [ $# -lt 2 ]; then
+		echo "Missing filename argument"
+		echo "Usage: run static|dynamic filename [dest-filename]"
+	elif [ $# -lt 3 ]; then
+		camlp4 $runner < "$2"
+	else
+		# write the output only if the program was parsed successfully
+		if result=$(camlp4 $translator < "$2"; exit ${PIPESTATUS[0]}); then
+			echo "$result" > "$3"
+		fi
+	fi
 fi
